# Generated by Django 5.2.8 on 2025-12-04 06:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the link', max_length=200)),
                ('slug', models.SlugField(help_text='Unique identifier for template usage', unique=True)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant Menu'), ('spa', 'Spa Menu'), ('room_dining', 'In-Room Dining'), ('transfer', 'Transfer Service'), ('board_menu', 'Board Menu'), ('other', 'Other')], default='other', max_length=50)),
                ('url', models.URLField(help_text='External URL or PDF link', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Link',
                'verbose_name_plural': 'External Links',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MailingListSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mailing List Subscriber',
                'verbose_name_plural': 'Mailing List Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+20 2 2795 0000', max_length=50)),
                ('whatsapp_number', models.CharField(default='+20 10 700 4785', max_length=50)),
                ('email', models.EmailField(default='restaurant.ramses@hilton.com', max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('hilton_honors_url', models.URLField(default='https://www.hilton.com/en/hilton-honors/member-benefits/')),
                ('hilton_honors_join_url', models.URLField(default='https://www.hilton.com/en/hilton-honors/join/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TransferOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_capacity', models.CharField(blank=True, max_length=100)),
                ('price_to_hotel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_from_hotel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('icon', models.CharField(default='🚗', help_text='Emoji icon', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transfer Option',
                'verbose_name_plural': 'Transfer Options',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, help_text='User phone number', max_length=20)),
                ('profile_picture', models.URLField(blank=True, help_text='Profile picture URL', max_length=500)),
                ('bio', models.TextField(blank=True, help_text='User biography')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('newsletter_subscription', models.BooleanField(default=False, help_text='Subscribe to newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='Image URL', max_length=500)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', max_length=500)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram page URL', max_length=500)),
                ('tiktok_url', models.URLField(blank=True, help_text='TikTok page URL', max_length=500)),
                ('email', models.EmailField(blank=True, help_text='Reservation email address', max_length=254)),
                ('opening_hours', models.CharField(blank=True, help_text='e.g., 12:00 PM - 11:00 PM', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Restaurant location/floor information', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='welcomeletter.externallink')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
