# Generated by Django 5.2.8 on 2025-12-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeletter', '0002_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded restaurant image', null=True, upload_to='restaurants/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (for demo)', max_length=500),
        ),
    ]
