# Generated by Django 5.2.8 on 2025-12-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeletter', '0003_restaurant_image_alter_restaurant_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_pdf',
            field=models.FileField(blank=True, help_text='Upload restaurant menu PDF', null=True, upload_to='restaurants/menus/'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurant Menu'), ('room_dining', 'In-Room Dining'), ('transfer', 'Transfer Service'), ('info', 'Info Page Link'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
