# Generated by Django 5.2.8 on 2025-12-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeletter', '0004_restaurant_menu_pdf_alter_externallink_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='+20 10 700 4785', max_length=50, verbose_name='Hotline Number'),
        ),
    ]
