# Generated by Django 5.2.8 on 2025-12-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeletter', '0005_alter_sitesettings_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='pdf',
            field=models.FileField(blank=True, help_text='Upload PDF file (takes priority over URL)', null=True, upload_to='external_links/'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='url',
            field=models.URLField(blank=True, help_text='External URL or PDF link', max_length=500),
        ),
    ]
