# Generated by Django 5.2.8 on 2025-12-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeletter', '0006_externallink_pdf_alter_externallink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='pdf',
            field=models.FileField(blank=True, help_text='Upload PDF file', null=True, upload_to='external_links/'),
        ),
    ]
